#%RAML 1.0 DataType
type: object



properties:
  sname:
    type: string
    required: true
    example: Raj
    minLength: 3
    maxLength: 10

  number:
    type: integer
    required: true
    example: 1234567890
    minimum: 0000000000
    maximum: 9999999999
       

  

  id:
    type: number
    required: true
    example: 100
    minimum: 3
    maximum: 500

  
  city:
    type: string
    required: true
    example: gnp
    minLength: 3
    maxLength: 10

  course:
    type: string
    required: true
    example: xyz
    minLength: 3
    maxLength: 6
      


      
      